name: CMake

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Setup environment
      run: |
        echo "PS5SDK=${{ github.workspace }}/ps5sdk" >> $GITHUB_ENV
        sudo apt install ninja-build

    - name: Show Clang version
      run: clang -v

    - name: Checkout
      uses: actions/checkout@main
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Checkout PS5SDK
      uses: actions/checkout@main
      with:
        repository: illusion0001/PS5SDK
        ref: nand-clang-16
        path: ${{ env.PS5SDK }}

    - name: Set commit version
      run: |
        echo "commit_ver=1.$(git rev-list HEAD --count)" >> $GITHUB_ENV
        echo "commit_hash=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

    - name: Build SDK
      working-directory: ${{ env.PS5SDK }}
      run: bash ./build.sh
           ls -l Plugin_samples/

    - name: Build etaHEN-SDK-Binaries
      run: bash ./build.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@main
      with:
        name: etaHEN-SDK-Binaries.tar
        path: ELF_samples/bin
              Plugin_samples/bin
